# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(docs/.*|docs/infracost\.html|README\.md)$
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - --args=--call-module-type=all
          - --args=--enable-rule=terraform_documented_variables
      - id: terraform_checkov
      - id: terraform_providers_lock
      - id: infracost_breakdown
        args:
          - --args=--path=.
          - --args=--show-skipped

  - repo: local
    hooks:
      - id: documentation
        name: Generate Documentation
        entry: make docs
        language: system
        pass_filenames: false
        stages: [pre-commit]
        description: "Generates graphs, cost analysis, and updates documentation"
